import { Analytics } from '@vercel/analytics/react';
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from '@mui/material';
import theme from './themes/theme';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Flashcard SaaS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <ThemeProvider theme={theme}>
      <html lang="en">
      <body className={inter.className}>{children}</body>
      </html>
    </ThemeProvider>
      <Analytics />

    </ClerkProvider>
    
  );
}
